In [1]:
import numpy as np


In [3]:
my_arr = np.arange(100000)
my_list = list(range(100000))


In [5]:
%time for i in range(10) : myarr2 = my_arr * 2

CPU times: total: 0 ns
Wall time: 3 ms


In [6]:
%time for i in range(10) : mylist2 = my_list * 2

CPU times: total: 31.2 ms
Wall time: 36 ms


In [23]:
a= np.array([1,2,3,4,5,6,7,8,9])

In [24]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
type(a)
a.shape

(9,)

In [14]:
id(a)

3277915264176

In [16]:
b= np.array([[1,2],[3,4],[5,6]])

In [17]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
type(b)

numpy.ndarray

In [31]:
c= np.array([1,2,3,4,5,6,7,8,9],ndmin=2)

In [40]:
c.shape


(1, 9)

In [33]:
d= np.array([1,2,3],dtype =complex)

In [34]:
d

array([1.+0.j, 2.+0.j, 3.+0.j])

In [35]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
b.shape

(3, 2)

In [37]:
e=b.reshape(2,3)

In [38]:
e

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
s= np.array([1,2,3,4,5,6,7,8,9])

In [42]:
t=s.reshape(3,3)

In [43]:
t

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
s.shape

(9,)

In [48]:
num=[1,2,3]
num=np.array(num)
print("1-d array :",num)
temp=num.reshape(3,1)
temp

1-d array : [1 2 3]


array([[1],
       [2],
       [3]])

In [51]:
arr=np.array([1,4,0,8,6,4,2,1,3,4,2,5,6,7,8,5,8])
np.bincount(arr)

array([1, 2, 2, 1, 3, 2, 2, 1, 3], dtype=int64)

In [53]:
m=np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23])
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [54]:
n=m.reshape(2,4,3)

In [55]:
n

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [56]:
x=np.array([1,2,3,4,5,6],dtype=np.int8)

In [57]:
x

array([1, 2, 3, 4, 5, 6], dtype=int8)

In [58]:
x.itemsize

1

In [59]:
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [60]:
y=x.copy()

In [61]:
y

array([1, 2, 3, 4, 5, 6], dtype=int8)

In [62]:
y.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [63]:
np.__version__

'1.21.5'

In [64]:
x=np.zeros((2,3),dtype=int)

In [65]:
x

array([[0, 0, 0],
       [0, 0, 0]])

In [66]:
x=np.empty([2,3],dtype=int)

In [67]:
x

array([[         0, 1072693248,          0],
       [1073741824,          0, 1074266112]])

In [68]:
x=np.ones(5)

In [69]:
x

array([1., 1., 1., 1., 1.])

In [70]:
x=np.ones([3,3],dtype=int)

In [71]:
x

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [72]:
d=np.eye(4)
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])